//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssingmentEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Trainees = new HashSet<Trainee>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime EntryAt { get; set; }
    
        public virtual ICollection<Trainee> Trainees { get; set; }
    }
}
